spring.application.name=FixMyTheru

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d94vhmpkh4rs73fr3i70-a.oregon-postgres.render.com:5432/fixmytheru_jg5n
spring.datasource.username=fixmytheru_jg5n_user
spring.datasource.password=yNWLk7yPL5ru2RrWvV2JcpXpvc6kr9WI
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server    
server.port=5731

# Session
spring.session.jdbc.initialize-schema=always

# JWT
app.jwt-secret=ThisIsMyVerySecureAndLongJwtSecretUsedOnlyForSigningTokensInSpringBootAndForItsSecurity!
app.jwt-expiration-milliseconds=36000000

# Logging
logging.level.org.springframework.security=DEBUG

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nsharan006@gmail.com
spring.mail.password=wrvb toll iywf knke
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true